Document: leseschlau
Title: Debian leseschlau Manual
Author: <insert document author here>
Abstract: This manual describes what leseschlau is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/leseschlau/leseschlau.sgml.gz

Format: postscript
Files: /usr/share/doc/leseschlau/leseschlau.ps.gz

Format: text
Files: /usr/share/doc/leseschlau/leseschlau.text.gz

Format: HTML
Index: /usr/share/doc/leseschlau/html/index.html
Files: /usr/share/doc/leseschlau/html/*.html
